name: Lint code & compile test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: kagchi/workflows/.github/workflows/lint-and-build-test.yaml@main
    